name: Publish Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: Release Type
        options:
          - stable
          - beta
          - alpha
      platform:
        type: choice
        description: Platform
        options:
          - both
          - fabric
          - neoforge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: true

      - name: Validate Gradle Wrapper Integrity
        uses: gradle/actions/wrapper-validation@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Release Build
        run: RELEASE_WORKFLOW=true ./gradlew build

      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-dev.jar;LICENSE'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Modrinth and Curseforge
        env:
          RELEASE_WORKFLOW: true
          RELEASE_TYPE: ${{ inputs.releaseType }}
          PLATFORM: ${{ inputs.platform }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: ./gradlew lithiumPublish
